app = "decen-main"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  DECEN_HOST = "0.0.0.0"
  PORT = "8080"

[[mounts]]
  source = "decen_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
